<?php

namespace Database\Seeders;

use App\Models\Inscricao;
use App\Models\InscricaoInstituicoes;
use App\Models\Instituicao;
use Illuminate\Database\Seeder;

class InscricaoSeeder extends Seeder
{
    public function run(): void
    {
        $instituicoes = Instituicao::pluck('id', 'name');

        $inscricoes = [
            [
                'name' => 'João da Silva',
                'cpf' => '11111111111',
                'rg' => '12345678',
                'birth_date' => '2005-03-15',
                'phone' => '12999990001',
                'email' => 'joao.silva@example.com',
                'cep' => '11660000',
                'address' => 'Rua Santa Cruz',
                'neighborhood' => 'Centro',
                'city' => 'Caraguatatuba',
                'number' => '123',
                'father_name' => 'José da Silva',
                'mother_name' => 'Maria da Silva',
                'observation' => 'Inscrição pendente para análise.',
                'status' => 'Incompleto',
                'course' => 'Engenharia Civil',
                'semester' => '3',
                'institution' => 'Universidade do Vale do Paraíba',
                'shift' => 2,
                'used_transport' => true,
                'days_of_week' => [1, 2, 3, 4, 5],
                'has_scholarship' => false,
            ],
            [
                'name' => 'Maria Oliveira',
                'cpf' => '22222222222',
                'rg' => '87654321',
                'birth_date' => '2006-05-20',
                'phone' => '12999990002',
                'email' => 'maria.oliveira@example.com',
                'cep' => '11662000',
                'address' => 'Avenida da Praia',
                'neighborhood' => 'Martim de Sá',
                'city' => 'Caraguatatuba',
                'number' => '456',
                'father_name' => 'Carlos Oliveira',
                'mother_name' => 'Ana Oliveira',
                'observation' => 'Documentação completa.',
                'status' => 'Aprovado',
                'course' => 'Direito',
                'semester' => '4',
                'institution' => 'Faculdade Módulo',
                'shift' => 2,
                'used_transport' => true,
                'days_of_week' => [1, 3, 5],
                'has_scholarship' => true,
                'scholarship_type' => 'Parcial',
            ],
            [
                'name' => 'Ana Clara Souza',
                'cpf' => '33333333333',
                'rg' => '33445566',
                'birth_date' => '2004-11-03',
                'phone' => '12999990003',
                'email' => 'ana.souza@example.com',
                'cep' => '11664000',
                'address' => 'Rua das Palmeiras',
                'neighborhood' => 'Indaiá',
                'city' => 'Caraguatatuba',
                'number' => '78',
                'father_name' => 'Roberto Souza',
                'mother_name' => 'Patrícia Souza',
                'observation' => 'Falta comprovante atualizado.',
                'status' => 'Rejeitado',
                'course' => 'Psicologia',
                'semester' => '2',
                'institution' => 'Universidade Paulista',
                'shift' => 1,
                'used_transport' => false,
                'days_of_week' => [2, 4],
                'has_scholarship' => false,
            ],
            [
                'name' => 'Lucas Henrique Martins',
                'cpf' => '44444444444',
                'rg' => '44556677',
                'birth_date' => '2003-07-12',
                'phone' => '12999990004',
                'email' => 'lucas.martins@example.com',
                'cep' => '11668000',
                'address' => 'Rua Projetada',
                'neighborhood' => 'Porto Novo',
                'city' => 'Caraguatatuba',
                'number' => '901',
                'father_name' => 'Henrique Martins',
                'mother_name' => 'Cláudia Martins',
                'observation' => 'Aguardando análise da secretaria.',
                'status' => 'Incompleto',
                'course' => 'Sistemas de Informação',
                'semester' => '6',
                'institution' => 'FATEC Caraguatatuba',
                'shift' => 2,
                'used_transport' => true,
                'days_of_week' => [1, 2, 3, 4],
                'has_scholarship' => false,
            ],
            [
                'name' => 'Fernanda Gomes Silva',
                'cpf' => '55555555555',
                'rg' => '55667788',
                'birth_date' => '2002-02-08',
                'phone' => '12999990005',
                'email' => 'fernanda.gomes@example.com',
                'cep' => '11670000',
                'address' => 'Rua Benedito Zacarias',
                'neighborhood' => 'Travessão',
                'city' => 'Caraguatatuba',
                'number' => '54',
                'father_name' => 'Marcos Silva',
                'mother_name' => 'Eliane Gomes',
                'observation' => 'Inscrição aprovada em teste.',
                'status' => 'Aprovado',
                'course' => 'Pedagogia',
                'semester' => '8',
                'institution' => 'UNIVESP Polo Caraguatatuba',
                'shift' => 1,
                'used_transport' => true,
                'days_of_week' => [6],
                'has_scholarship' => true,
                'scholarship_type' => 'Integral',
            ],
        ];

        foreach ($inscricoes as $data) {
            $inscricao = Inscricao::updateOrCreate(
                ['cpf' => $data['cpf']],
                [
                    'name' => $data['name'],
                    'rg' => $data['rg'],
                    'birth_date' => $data['birth_date'],
                    'phone' => $data['phone'],
                    'email' => $data['email'],
                    'cep' => $data['cep'],
                    'address' => $data['address'],
                    'neighborhood' => $data['neighborhood'],
                    'city' => $data['city'],
                    'number' => $data['number'],
                    'father_name' => $data['father_name'],
                    'mother_name' => $data['mother_name'],
                    'observation' => $data['observation'],
                    'status' => $data['status'],
                    'accepted_terms' => true,
                    'accepted_terms_2' => true,
                ],
            );

            InscricaoInstituicoes::updateOrCreate(
                ['inscricao_id' => $inscricao->id],
                [
                    'course' => $data['course'],
                    'semester' => $data['semester'],
                    'expected_completion' => now()->addYears(2)->toDateString(),
                    'instituicao_id' => $instituicoes->get($data['institution']),
                    'shift' => $data['shift'],
                    'city_destination' => 'Caraguatatuba',
                    'used_transport' => $data['used_transport'],
                    'days_of_week' => $data['days_of_week'],
                    'has_scholarship' => $data['has_scholarship'],
                    'scholarship_type' => $data['scholarship_type'] ?? null,
                ],
            );

        }
    }
}
